[package]
name = "nginx-log-analyzer"
version = "0.1.0"
authors = ["BlankZhu <707310837@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
regex = "1"
clap = "3.0.0-beta.2"
